---
- hosts: localhost
  connection: local
  tasks:
  - name: install packages
    become: true
    tags: packages
    ignore_errors: true
    block:
    - name: install vim
      package:
        name: vim
    - name: install powerline
      package:
        name: powerline
    - name: install tldr
      package:
        name: tldr
    - name: install ag
      package:
        name: silversearcher-ag
    - name: install lsd
      apt:
        deb: https://github.com/lsd-rs/lsd/releases/download/v1.1.2/lsd-musl_1.1.2_amd64.deb
    - name: install htop
      package:
        name: htop
    - name: install fzf
      package:
        name: fzf
    - name: install fd
      package:
        name: fd-find
    - name: install bat
      package:
        name: bat
    - name: install neofetch
      package:
        name: neofetch
    - name: install git
      package:
        name: git

  #config
  - name: bash aliases 
    become: true
    tags: aliases
    lineinfile:
      path: /etc/bash.bashrc
      line: '{{ item }}'
    with_items: 
      - "source /usr/share/doc/fzf/examples/key-bindings.bash"
      - "alias l='lsd -al --group-directories-first '"
      - "alias v='vim'"
      - "alias cat='batcat'"
      - "alias fd='fdfind'"
      - "alias ag='ag --color-path  35 --color-line-number 34'"
  - name: unzip dotfiles
    tags: dotfiles
    unarchive:
      src: https://github.com/MrZaus/dotfiles/archive/refs/heads/main.zip
      dest: "{{ ansible_env.HOME }}/"
      remote_src: yes
  - name: copy dotfiles to home dir
    tags: dotfiles
    copy:
      src: "{{ item }}"
      dest: ~/
      backup: true
      remote_src: yes
    with_fileglob:
      - "{{ ansible_env.HOME }}/dotfiles-main/.*"
  - name: list
    tags: dotfiles
    raw: ls -asl ~
  - name: install vim vundle plugin
    tags: dotfiles
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim
